name: 🌘 Nightly Releases

on:
  schedule:
    - cron: '23 0 * * *'
  workflow_dispatch:

env:
  TARGET_REPO: OpenVic-Simulation-nightly-builds

permissions: {}

jobs:
  nightly-check:
    name: Check for new commits
    if: github.event_name == 'workflow_dispatch' || !vars.DISABLE_SIM_NIGHTLYS
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.check_for_new_commits.outputs.commit }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Retrieve HEAD commit hash
        id: head
        shell: bash
        run: echo "head=$(git rev-parse HEAD)" | tee -a "${GITHUB_OUTPUT}"

      - name: Cache nightly commit hash
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
        with:
          path: .nightly_commit_hash
          key: release-nightly-${{ steps.head.outputs.head }}
          restore-keys: |
            release-nightly-

      - name: Check for new commits
        id: check_for_new_commits
        shell: bash
        run: |
          relevant_files=(
            "deps/*"
            "misc/*"
            "scripts"
            "src/*.hpp"
            "src/*.cpp"
            ':!src/openvic-simulation/pch.hpp'
            ':!src/openvic-simulation/pch.cpp'
            "pyproject.toml"
            "SConstruct"
            ".github/workflows/builds.yml"
            ".github/actions/openvic-sim-release/action.yml"
            ".github/workflows/nightly-releases.yml"
            ".github/actions/openvic-sim-release/action.yml"
            ".github/actions/openvic-sim-release/nightly-release-notes-configuration.json"
          )
          if [[ -f .nightly_commit_hash ]]; then
            limit_args=(
              "$(cat .nightly_commit_hash)..HEAD"
            )
          else
            limit_args=(
              --since="24 hours ago"
            )
          fi
          echo "commit=$(git log --format=%H -1 "${limit_args[@]}" -- "${relevant_files[@]}")" | tee -a "${GITHUB_OUTPUT}"

      - name: Record new nightly commit hash
        env:
          HEAD: ${{ steps.head.outputs.head }}
        shell: bash
        run: echo "${HEAD}" | tee .nightly_commit_hash

  nightly-build:
    name: Build ${{ matrix.name }}
    needs: nightly-check
    # if: needs.nightly-check.outputs.commit
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write  # May be needed to publish release
      id-token: write  # Needed for trusted publishing
    strategy:
      fail-fast: false
      matrix:
        include:
          # - identifier: windows-release
          #   os: windows-latest
          #   name: 🏁 Windows Release
          #   target: template_release
          #   platform: windows
          #   arch: x86_64
          #   scons-flags: ''

          - identifier: macos-release
            os: macos-latest
            name: 🍎 macOS (universal) Release
            target: template_release
            platform: macos
            arch: universal
            scons-flags: 'lto=full'

          - identifier: linux-release
            os: ubuntu-latest
            name: 🐧 Linux Release
            runner: ubuntu-22.04
            target: template_release
            platform: linux
            arch: x86_64
            scons-flags: 'lto=full use_static_cpp=yes'

    steps:
      - name: Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false

      - name: Build
        uses: ./.github/actions/openvic-sim-build
        with:
          identifier: ${{ matrix.identifier }}
          target: ${{ matrix.target }}
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          scons-flags: use_hot_reload=no build_ovsim_tests=no debug_symbols=yes ${{ matrix.scons-flags }}

  publish-nightly-release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: nightly-build
    permissions:
      contents: write  # May be needed to publish release
      id-token: write  # Needed for trusted publishing

    steps:
      - name: Shallow Clone
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1 # See: https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/
          fetch-tags: true

      - name: Retrieve master/nightly release tag info
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "LAST_MASTER_TAG_INFO=$(gh release list -L 1 --json tagName,publishedAt --jq '.[0]')" >> $GITHUB_ENV
          echo "LAST_NIGHTLY_TAG_INFO=$(gh release list -L 1 -R OpenVicProject/${{ env.TARGET_REPO }} --json tagName,publishedAt --jq '.[0]')" >> $GITHUB_ENV

      - name: Query master/nightly release tag info for dates
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "LAST_MASTER_TAG_PUB_DATE=$(jq -r ".publishedAt" <<< "$LAST_MASTER_TAG_INFO")" >> $GITHUB_ENV
          echo "LAST_NIGHTLY_TAG_PUB_DATE=$(jq -r ".publishedAt" <<< "$LAST_NIGHTLY_TAG_INFO")" >> $GITHUB_ENV

      - name: Process master/nightly release tag dates
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "LAST_MASTER_TAG_PUB_SEC=$(date -d $LAST_MASTER_TAG_PUB_DATE +%s)" >> $GITHUB_ENV

          if [[ ! -z $LAST_NIGHTLY_TAG_PUB_DATE ]]; then
            echo "LAST_NIGHTLY_TAG_PUB_SEC=$(date -d $LAST_NIGHTLY_TAG_PUB_DATE +%s)" >> $GITHUB_ENV
          else
            echo "LAST_NIGHTLY_TAG_PUB_SEC=0" >> $GITHUB_ENV
          fi

      - name: Get FROM_REF, LATEST_TAG, and COMMIT_HASH from latest release
        if: env.LAST_MASTER_TAG_PUB_SEC >= env.LAST_NIGHTLY_TAG_PUB_SEC
        run: |
          LATEST_TAG=$(jq -r '.tagName' <<< "$LAST_MASTER_TAG_INFO")
          echo "::debug::LATEST_TAG=$LATEST_TAG"

          COMMIT_HASH=$(git rev-parse --verify -q $LATEST_TAG)
          echo "::debug::COMMIT_HASH=$COMMIT_HASH"

          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "FROM_REF=$LATEST_TAG" >> $GITHUB_ENV

      - name: Get FROM_REF, LATEST_TAG, and COMMIT_HASH from latest release
        if: env.LAST_MASTER_TAG_PUB_SEC < env.LAST_NIGHTLY_TAG_PUB_SEC
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          LATEST_TAG=$(jq -r '.tagName' <<< "$LAST_NIGHTLY_TAG_INFO")
          echo "::debug::LATEST_TAG=$LATEST_TAG"

          LATEST_RELEASE_BODY=$(gh release view $LATEST_TAG -R OpenVicProject/${{ env.TARGET_REPO }} --json body --jq '.body')
          echo "::debug::LATEST_RELEASE_BODY=$LATEST_RELEASE_BODY"

          # Keep up to date with .github/actions/openvic-sim-release/nightly-release-notes-configuration.json
          HASH_OF_TAG=$(grep -oP 'Generated from: OpenVicProject/OpenVic-Simulation@\K[a-zA-Z0-9]+' <<< "$LATEST_RELEASE_BODY")
          echo "::debug::HASH_OF_TAG=$HASH_OF_TAG"

          COMMIT_HASH=$(git rev-parse --verify -q $HASH_OF_TAG)
          echo "::debug::COMMIT_HASH=$COMMIT_HASH"

          if [[ -z $COMMIT_HASH ]]; then
            echo "::error file=.github/workflows/nightly-releases.yml,line=201,endLine=201::Could not find commit for hash $HASH_OF_TAG."
            exit 1
          fi

          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "FROM_REF=$COMMIT_HASH" >> $GITHUB_ENV

      - name: Process release into TAG_NAME
        run: |
          declare $(awk '
            split($0, sections, /[-+]?/) split(sections[1], version, /\./) split(sections[2], prerelease, /\./) {
              prerelease_version=prerelease[2]
            } END {
              version_major=int(version[1])
              version_minor=int(version[2])
              if (prerelease[1] == "") {
                version_minor=version_minor+1
              }

              version_core=version_major"."version_minor
              print "VERSION_CORE="version_core
            }
          ' <<< "$LATEST_TAG")
          echo "::debug::VERSION_CORE=$VERSION_CORE"

          echo "TAG_NAME=$VERSION_CORE-nightly.$(date +%Y.%m.%d)+${{ github.sha }}" >> $GITHUB_ENV

      - name: Publish Nightly Release
        uses: ./.github/actions/openvic-sim-release
        with:
          latest: true
          nightly-release: true
          tag-name: ${{ env.TAG_NAME }}
          from-ref: ${{ env.FROM_REF }}
          from-tag: ${{ env.LATEST_TAG }}
          to-ref: ${{ github.sha }}
          target-repo: ${{ env.TARGET_REPO }}
          src-token: ${{ secrets.GITHUB_TOKEN }}
          target-token: ${{ secrets.NIGHTLY_RELEASE_REPO_PAT }}

